In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import keras
from keras.models import Sequential,Model
from keras.optimizers import Adam
from keras.layers import Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D, GlobalMaxPooling2D
from keras.utils.np_utils import to_categorical


Using TensorFlow backend.


In [2]:
x=list()
y=list()
for i in range(1,111):
    img=cv2.imread("New Fire Images/%d.jpg"%i,1)
    img=cv2.resize(img,(50,50))
    img=np.float32(img)
    img/=255.0
    img = img.reshape(50, 50, 3)
    img=img.tolist()
    x.append(img)
    y.append(1)
for i in range(1,543):
    img=cv2.imread("new normal/%d.jpg"%i,1)
    img=cv2.resize(img,(50,50))
    img=np.float32(img)
    img/=255.0
    img = img.reshape(50, 50, 3)
    img=img.tolist()
    x.append(img)
    y.append(0)
x=np.asarray(x)
y=np.asarray(y)
y=to_categorical(y)

In [3]:
def NN():
    model = Sequential()
    model.add(Conv2D(16, (5,5),input_shape=(50,50,3),padding='same', activation='sigmoid'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Conv2D(8, (3, 3), activation = 'sigmoid',padding = 'same'))
    model.add(MaxPooling2D(pool_size = (2,2)))
    model.add(Flatten())
    model.add(Dense(128, activation = 'sigmoid'))
    model.add(Dense(64, activation = 'sigmoid'))
    model.add(Dense(2, activation = 'softmax'))
    model.compile(Adam(lr = 0.001), loss = 'binary_crossentropy', metrics = ['accuracy'])
    return model

In [4]:
model=NN()
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 50, 50, 16)        1216      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 25, 25, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 25, 25, 8)         1160      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 12, 12, 8)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1152)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               147584    
_________________________________________________________________
dens

In [5]:
model.fit(x,y,epochs=20,batch_size=5,verbose=1,shuffle=True,validation_data=(x,y))

Instructions for updating:
Use tf.cast instead.
Train on 652 samples, validate on 652 samples
Epoch 1/20
652/652 [==============================] - 9s 14ms/step - loss: 0.4667 - acc: 0.8236 - val_loss: 0.4698 - val_acc: 0.8313
Epoch 2/20
652/652 [==============================] - 2s 4ms/step - loss: 0.4650 - acc: 0.8313 - val_loss: 0.4499 - val_acc: 0.8313
Epoch 3/20
652/652 [==============================] - 2s 3ms/step - loss: 0.4372 - acc: 0.8344 - val_loss: 0.3978 - val_acc: 0.8497
Epoch 4/20
652/652 [==============================] - 1s 2ms/step - loss: 0.3844 - acc: 0.8497 - val_loss: 0.3751 - val_acc: 0.8497
Epoch 5/20
652/652 [==============================] - 1s 2ms/step - loss: 0.3668 - acc: 0.8436 - val_loss: 0.3427 - val_acc: 0.8543
Epoch 6/20
652/652 [==============================] - 1s 2ms/step - loss: 0.3589 - acc: 0.8374 - val_loss: 0.3326 - val_acc: 0.8574
Epoch 7/20
652/652 [==============================] - 1s 2ms/step - loss: 0.3324 - acc: 0.8589 - val_loss: 0.3437

In [6]:
x

array([[[[0.03137255, 0.03137255, 0.03137255],
         [0.03529412, 0.03529412, 0.03529412],
         [0.03137255, 0.03137255, 0.03137255],
         ...,
         [0.0627451 , 0.04705882, 0.03921569],
         [0.0627451 , 0.04313726, 0.03921569],
         [0.05882353, 0.04313726, 0.03921569]],

        [[0.02352941, 0.02352941, 0.02352941],
         [0.02352941, 0.02352941, 0.02352941],
         [0.01960784, 0.01960784, 0.01960784],
         ...,
         [0.04313726, 0.03529412, 0.03529412],
         [0.04313726, 0.03529412, 0.03137255],
         [0.04313726, 0.03529412, 0.03137255]],

        [[0.00784314, 0.01568628, 0.01960784],
         [0.00784314, 0.01568628, 0.01960784],
         [0.00784314, 0.01568628, 0.01960784],
         ...,
         [0.02745098, 0.02745098, 0.02745098],
         [0.02352941, 0.02352941, 0.02352941],
         [0.02745098, 0.02745098, 0.02745098]],

        ...,

        [[0.58039218, 0.51764709, 0.4627451 ],
         [0.71764708, 0.64313728, 0.56078434]

In [7]:
model.predict(x[76].reshape(1,50,50,3))

array([[0.04304338, 0.9569566 ]], dtype=float32)

In [8]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [9]:
model.save('val96.h5')